### ISSUE TITLE
Amazon Prime Video App

### ISSUE THREAD

**Issue by Tysinger** [MSF-Jarvis/viscerion#110]
Amazon Prime Video App does not seem to get whitelisted correctly. Netflix seems to work, but Prime refuses to play videos based upon 'Geo IP.'

**Comment by MSF-Jarvis** [comment]
It's more likely Amazon Prime having identified your VPN provider's servers than an app failure considering you say Netflix works just fine. The app does not differentiate between different applications while processing whitelists/blacklists.

**Comment by MSF-Jarvis** [comment]
Invalid issue based on available info and no follow-up from OP.
