### ISSUE TITLE
[FEATURE] Android TV Support

### ISSUE THREAD

**Issue by kaambiz** [MSF-Jarvis/viscerion#116]
Will there be any support for Android TV at any time?

**Comment by MSF-Jarvis** [comment]
I don't have any device in this form factor so it's pretty hard to push out support, plus I don't have any prior experience with other it either. I'll keep this open since I'd love to work on it at some point but for now it's not a priority.

**Comment by molgar** [comment]
As far as I can tell, Viscerion 4.0 works on Android TV, but for the fact that I can't find a way to add a VPN without a QR Code, which can't be done without a camera.

**Comment by kaambiz** [comment]
> As far as I can tell, Viscerion 4.0 works on Android TV. The only issue I've found is an interface one, as one could expect. The + button only shows the option to create from scratch.

It does install and run fine-ish (going to settings crashes the app). As for importing the config it could be done through "Create from file or archive" which seems absent or rather not visible on TV form factor (the only option I can see is "Create from Scratch").

**Comment by MSF-Jarvis** [comment]
> > As far as I can tell, Viscerion 4.0 works on Android TV. The only issue I've found is an interface one, as one could expect. The + button only shows the option to create from scratch.
> 
> It does install and run fine-ish (going to settings crashes the app). As for importing the config it could be done through "Create from file or archive" which seems absent or rather not visible on TV form factor (the only option I can see is "Create from Scratch").

The settings crash I believe is the same as in #128, I'm still investigating it. About the import bottom sheet, I have recently acquired a Xiaomi smart TV which seems to run Android apps semi decently so I'm going to try and work towards this.

**Comment by MSF-Jarvis** [comment]
@molgar @kaambiz I think I've solved the bottom sheet problem, please try [this](https://download.msfjarvis.website/viscerion/viscerion_4.0.0-85-g3e5e6b071d13-release.apk) out and see if it resolves the issue for you. You should be able to upgrade from the Play Store build just fine. Thanks a lot for all the feedback so far, it's been immensely helpful :)

**Comment by molgar** [comment]
I can't install the attached apk. Application not installed is what I get when I try to install it on top of the 4.0 release.

**Comment by MSF-Jarvis** [comment]
> I can't install the attached apk. Application not installed is what I get when I try to install it on top of the 4.0 release.

Ah my bad, Play Store builds use [App Bundles](https://developer.android.com/platform/technology/app-bundle) which are resigned by Google Play on their servers. Here's a debug build that can be installed alongside: [viscerion_4.0.0-93-gf466c29ad203-debug.apk](https://download.msfjarvis.website/viscerion/viscerion_4.0.0-93-gf466c29ad203-debug.apk)

**Comment by molgar** [comment]
Same thing with that new build. Can't install

**Comment by MSF-Jarvis** [comment]
Ugh what the hell... Can you try installing it on to your phone with ADB and send me the error?

**Comment by molgar** [comment]
Sorry, I on iPhone. I do have an android phone lying around though. What's ADB?

**Comment by MSF-Jarvis** [comment]
> Sorry, I'm on iPhone. I do have an android phone lying around though. What's ADB?

Oh well, I'm just gonna try to reproduce the issue locally then I guess. ADB is explained [here](https://developer.android.com/studio/command-line/adb).

**Comment by geekinaboxx** [comment]
Here you go:

`./adb install ~/Downloads/viscerion_4.0.0-95-gaabca423b0a8-debug.apk
* daemon not running; starting now at tcp:5037
* daemon started successfully
Performing Streamed Install
adb: failed to install /Users/aleemtectonic/Downloads/viscerion_4.0.0-95-gaabca423b0a8-debug.apk: Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]`

**Comment by MSF-Jarvis** [comment]
> Here you go:
> 
> ```
> ./adb install ~/Downloads/viscerion_4.0.0-95-gaabca423b0a8-debug.apk
> * daemon not running; starting now at tcp:5037
> * daemon started successfully
> Performing Streamed Install
> adb: failed to install /Users/aleemtectonic/Downloads/viscerion_4.0.0-95-gaabca423b0a8-debug.apk: Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]
> ```

Hmm, that's gonna be a problem. Try [this](https://download.msfjarvis.website/viscerion/viscerion_4.0.0-103-g036e6a7db374-debug.apk) one please.

**Comment by geekinaboxx** [comment]
```
./adb install ~/Downloads/viscerion_4.0.0-103-g036e6a7db374-debug.apk
Performing Streamed Install
Success
```

winner. Will sideload onto my Android TV if I get chance over the next few days.

**Comment by MSF-Jarvis** [comment]
> ```
> ./adb install ~/Downloads/viscerion_4.0.0-103-g036e6a7db374-debug.apk
> Performing Streamed Install
> Success
> ```
> winner. Will sideload onto my Android TV if I get chance over the next few days.

So I can't rollout with Q support. That's a bummer...

**Comment by molgar** [comment]
> winner

I was also able to install it on my Android TV set.

**Comment by MSF-Jarvis** [comment]
> > winner
> 
> I was also able to install it on my Android TV set.

Does the Create button correctly show the bottom sheet now?

**Comment by molgar** [comment]
Yes, it does. I can either create from scratch, import from a file, or create from a QR-code.

**Comment by MSF-Jarvis** [comment]
> Yes, it does. I can either create from scratch, import from a file, or create from a QR-code.

![image](https://user-images.githubusercontent.com/13348378/56162028-abbf4080-5fe8-11e9-8ef5-2ce501dc097e.png)
