### ISSUE TITLE
[FEATURE] Live log

### ISSUE THREAD

**Issue by ybinnenwegin2ip** [MSF-Jarvis/viscerion#122]
**Is your feature request related to a problem? Please describe.**
When issues arise while trying to connect to a VPN server it would be nice to have a live log of what the exact issue is. Rather than having to go into the settings, exporting the logs and opening them in a text editor on your phone, you could immediately see what's going on.

**Describe the solution you'd like**
A textfield with the live log, this field would automatically update as Wireguard provides more logs. Possibly (but not required at all) would be colour highlighting.

**Describe alternatives you've considered**
An alternative solution would be to have a more easily accessible 'export logs' button (so you don't have to go into settings, export logs). In addition to that, rather than saving the log, it could immediately open in a text editor/HTML viewer.

**Additional context**
Ugly mockup I made
![mockup](https://i.imgur.com/7jfd5Gu.png)

**Comment by MSF-Jarvis** [comment]
Are you sure you want the log to be there? They're not filtered based on the current interface so it'd be kind of redundant. I was thinking maybe an overflow menu item to take you to the full log viewer with an export button.

**Comment by ybinnenwegin2ip** [comment]
> Are you sure you want the log to be there? They're not filtered based on the current interface so it'd be kind of redundant. I was thinking maybe an overflow menu item to take you to the full log viewer with an export button.

That'd be fine as well actually! :)
