### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by MSF-Jarvis** [MSF-Jarvis/viscerion#128]
This issue will be maintained as a constantly updated bugtracker
to reflect issues that have been discovered and not patched yet.
Users are encouraged to report issues here first and then escalate
them to separate issues once I flag the issue as critical enough.

List of issues known and unpatched so far

### Resolved in 5.0.0

- ~[x] Settings exits abruptly on first run, works fine after.~
- ~[x] Exclusions count is unreliable~

**Comment by recod4** [comment]
I don't think it's important but when you exclude some apps it still shows "0 excluded apps", it's stuck at 0. Though the feature itself works fine.

**Comment by MSF-Jarvis** [comment]
> I don't think it's important but when you exclude some apps it still shows "0 excluded apps", it's stuck at 0. Though the feature itself works fine.

I think I fixed it with 74dab27babfa and f2ba771c960a, try the build from [here](https://download.msfjarvis.website/viscerion/viscerion_4.0.0-85-g3e5e6b071d13-release.apk) and re-confirm. You might need to export and re-import tunnels.

**Comment by recod4** [comment]
I tried the .103 build and looks like it's still stuck here. App was clean installed.

**Comment by MSF-Jarvis** [comment]
> I tried the .103 build and looks like it's still stuck here. App was clean installed.

Thanks, I'll investigate it.

**Comment by MSF-Jarvis** [comment]
Exclusions count fixed with 5843b63fd6718e64e9ffc91e4850eb19555af001

**Comment by MSF-Jarvis** [comment]
Settings crash fixed with https://github.com/MSF-Jarvis/viscerion/commit/511475bb5e4a01bcd1c0c184f713b97492cd7214. Onwards to a new stable release!
