### ISSUE TITLE
Security considerations for Viscerion

### ISSUE THREAD

**Issue by MSF-Jarvis** [MSF-Jarvis/viscerion#135]
Considering this is a VPN app and users probably do things ranging from
whistleblowing to bringing a different flavour to porn recommendations
using it, it would be unwise to not give some thought to this aspect of
things.

What would you as a user like to see in Viscerion to ensure that the app
atleast *feels* secure to you?

**Comment by divadsn** [comment]
An option to "rebuild" the app with an undetectable package name, so it can be hidden?

**Comment by MSF-Jarvis** [comment]
> An option to "rebuild" the app with an undetectable package name, so it can be hidden?

Is there any actual purpose to it though? Are apps actually scanning for the Viscerion package name?

**Comment by lazerl0rd** [comment]
The ability to do https://github.com/MSF-Jarvis/viscerion/issues/66 to a WebDAV instance instead of Google's servers.

**Comment by Skrilltrax** [comment]
Ask @taviso to audit it :laughing:
