### ISSUE TITLE
[FEATURE] Dark mode?

### ISSUE THREAD

**Issue by lazerl0rd** [MSF-Jarvis/viscerion#137]
Other than just an AMOLED theme. If possible, thanks.

**Comment by lazerl0rd** [comment]
Thanks*

**Comment by MSF-Jarvis** [comment]
I'll be redoing the entire theme soon, the black background is definitely going.

**Comment by lazerl0rd** [comment]
> I'll be redoing the entire theme soon, the black background is definitely going.

Perfection
