### ISSUE TITLE
[BUG] Tasker Tunnel Up intent not working when app not started recently / not in foreground

### ISSUE THREAD

**Issue by Froghut** [MSF-Jarvis/viscerion#142]
I have it set up in Tasker to send the tunnel up intent when I disconnect from my home wifi. I even tried starting the app, wait a few seconds and then send the intent, but this also does not work reliably. Perhaps it only works when the screen is on?
I'm on Android 9 on a Moto X4.

**Comment by MSF-Jarvis** [comment]
I'll take a look, thanks for the report. Please try to retain the issue template next time, it makes my job easier :)
