### ISSUE TITLE
[BUG] Tasker integration doesn't work in 5.1.0

### ISSUE THREAD

**Issue by cf00** [MSF-Jarvis/viscerion#148]
**Describe the bug**
Since upgrading to 5.1.0 the Tasker integration doesn't work anymore. When I downgrade to 5.0.0. everything is working fine again.

**To Reproduce**
1. Send an intent from Tasker
```
Action: me.msfjarvis.viscerion.SET_TUNNEL_UP
Extra: tunnel_name:xyz
Extra: integration_secret:secret
Package: me.msfjarvis.viscerion
Class: com.wireguard.android.services.TaskerIntegrationReceiver
Target: Broadcast Receiver
```
2. Nothing happens

**Expected behavior**
Tunnel should go up or down

**Device information (please complete the following information):**
 - Device: Samsung Galaxy S10
 - OS: stock Android 9
 - Backend: Go userspace backend v.0.0.20190517
 - Version 5.1.0

**Comment by MSF-Jarvis** [comment]
After enabling the tasker integration, please go to `Settings > Developer Options > Running Services` and check if there is a Viscerion process listed. If the service correctly started, you should see something like [this](https://i.imgur.com/i7XQRr4.png) on your device too.

**Comment by cf00** [comment]
Thanks for the quick response.

No, there is no Viscerion process shown under Running Services. But If I enable "Show cached processes" I see a Viscerion process shown as "Cached background process".

**Comment by MSF-Jarvis** [comment]
> Thanks for the quick response.
> 
> No, there is no Viscerion process shown under Running Services. But If I enable "Show cached processes" I see a Viscerion process shown as "Cached background process".

That's weird... I'll revert the service rewrite and send you a test build in a few minutes.

**Comment by cf00** [comment]
Ok, I tried now to restart the phone and the process showed up with "1 process and 1 service" immediately after restarting - but it was still not responding to the intent. And just now the process disappeared again from the list.

**Comment by MSF-Jarvis** [comment]
Alright thanks, I've confirmed [this](https://download.msfjarvis.website/viscerion/viscerion_5.1.0-4-gf99dd500894a-release.apk) build still works on my device so if it resolves the problem for you I'll release a new version on the Play Store immediately.

**Comment by cf00** [comment]
Yes, this seems to work now!

Thanks a lot for your great support. 5 stars are coming on the Play Store :-)

**Comment by MSF-Jarvis** [comment]
> Yes, this seems to work now!
> 
> Thanks a lot for your great support. 5 stars are coming on the Play Store :-)

Thank you! Pushing the update now :)
