### ISSUE TITLE
Automatic enabling VPN when connecting to certain WiFi networks

### ISSUE THREAD

**Issue by YaroST12** [MSF-Jarvis/viscerion#24]
Pie connects automatically, even if WiFi in UI is off, would be nice to have protected tunnel when this happens.

**Comment by geekinaboxx** [comment]
Perhaps I've misunderstood the feature request, but I think you can achieve this using Tasker on Android with https://github.com/MSF-Jarvis/viscerion/issues/111

For example, I have a Tasker profile that enables WireGuard when I'm connected to an unknown SSID (or when I'm on 4G), and then disconnects when I'm on a known SSID (e.g. my home network).

**Comment by MSF-Jarvis** [comment]
Tasker support is on Play Store, this issue can be addressed with it. Closing.

**Comment by geekinaboxx** [comment]
I use Viscerion with Tasker, and it's working really nicely. Hopefully Android Q won't cripple Automation apps like Tasker to the extent that they can no longer function as they do currently.

On a related note, the official Wireguard app for iOS recently added exactly this feature (SSID whitelist / blacklist).

**Comment by lunim** [comment]
@MSF-Jarvis
Would it be possible to get this added without the need of tasker?

**Comment by MSF-Jarvis** [comment]
Getting current Wi-Fi network requires location permissions as well as location being explicitly enabled by the user (on Android 9.0 and above), so it's not worth the effort to add in the app. Tasker will have to do I'm afraid.

**Comment by lunim** [comment]
It looks like Android Q might break this functionality, if so, could this be added directly to the app?  https://developer.android.com/preview/privacy/background-activity-starts

**Comment by MSF-Jarvis** [comment]
> It looks like Android Q might break this functionality, if so, could this be added directly to the app? [developer.android.com/preview/privacy/background-activity-starts](https://developer.android.com/preview/privacy/background-activity-starts)

Again, the app is going to require location permissions to make this happen. I'm very hesitant to introduce extra permissions, especially while I'm working towards eliminating the usage of [READ_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE) (https://github.com/MSF-Jarvis/viscerion/commit/a79d22e20287d1c74483bb917c106b5b0f7fd18a).
